SUPABASE_URL = "https://semmrifxxujehiqbswqx.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbW1yaWZ4eHVqZWhpcWJzd3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDM2NjgsImV4cCI6MjA3MDIxOTY2OH0.0M0_WwM2KndUEINLUstWrqNmctVly9fXCPd6Bqfc5wI"
